# Generated by Django 4.2.5 on 2024-06-30 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="shit", verbose_name="うんちの画像"
                    ),
                ),
                ("r", models.IntegerField(blank=True, null=True, verbose_name="R")),
                ("g", models.IntegerField(blank=True, null=True, verbose_name="G")),
                ("b", models.IntegerField(blank=True, null=True, verbose_name="B")),
                (
                    "condition",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "良い"), (2, "悪い")],
                        null=True,
                        verbose_name="コンディション",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="投稿日",
                    ),
                ),
            ],
            options={
                "db_table": "poop_image",
            },
        ),
    ]
