# Generated by Django 4.2.5 on 2024-06-30 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="medical",
            table="poop",
        ),
    ]
