# Generated by Django 4.2.5 on 2024-06-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0002_alter_medical_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medical",
            name="condition",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="コンディション"
            ),
        ),
    ]
